# 수업에 사용될 라이브러리 설치

In [4]:
dir# 윈도우 사용자의 경우 -> dir 

<function dir>

In [ ]:
pip install numpy

In [5]:
!pip install -r requirements.txt

^C


# Numpy 소개

In [6]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [8]:
import numpy as np

## ndarray dtype

In [9]:
# 파이썬 list 와 비슷한 속성을 가짐
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [10]:
type(a)

numpy.ndarray

In [11]:
# indexing이 list와 방식이 같음
a[0]

1

In [13]:
a.

array([1, 2, 3])

- append() 같은 함수가 없음 -> 즉, python의 list와는 다른 data type임

## Universal function

In [ ]:
# vectorize function이랑 같음
#

In [14]:
a = [1, 2, 3]
b = [4, 5, 6]

new_list = []
for e1, e2 in zip(a, b):
    new_list.append(e1 + e2)
new_list

[5, 7, 9]

In [15]:
a + b

[1, 2, 3, 4, 5, 6]

In [16]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [17]:
# 길이가 길어도 근사적으로 1초가 걸린다
a + b

array([5, 7, 9])

In [ ]:
# np.sum
# np.abs
# np.log
# np.exp
# np.isnan
# ...

- n차원 array

In [18]:
a = np.array([  [1, 2],  [3, 4]   ])
a

array([[1, 2],
       [3, 4]])

In [19]:
# readability 높이기
a = np.array(
    [
        [1, 2],
        [3, 4],
    ]
)

In [20]:
a[0][1]

2

In [21]:
a + a

array([[2, 4],
       [6, 8]])